"""reviews table is create and linked with user and books

Revision ID: 2086ccd30b53
Revises: 3ee656b08a9b
Create Date: 2025-11-08 15:52:21.721491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2086ccd30b53'
down_revision: Union[str, Sequence[str], None] = '3ee656b08a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('book_uid', sa.UUID(), nullable=True))
    op.add_column('reviews', sa.Column('user_uid', sa.UUID(), nullable=True))
    op.add_column('reviews', sa.Column('review_text', sa.String(), nullable=False))
    op.add_column('reviews', sa.Column('rating', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('reviews', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'reviews', ['uid'])
    op.create_foreign_key(None, 'reviews', 'books', ['book_uid'], ['bid'], ondelete='SET NULL')
    op.create_foreign_key(None, 'reviews', 'users', ['user_uid'], ['uid'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='unique')
    op.drop_column('reviews', 'updated_at')
    op.drop_column('reviews', 'created_at')
    op.drop_column('reviews', 'rating')
    op.drop_column('reviews', 'review_text')
    op.drop_column('reviews', 'user_uid')
    op.drop_column('reviews', 'book_uid')
    # ### end Alembic commands ###
