"""tags and book tag table is create and relationship with books and tags table

Revision ID: 41af09a4efe2
Revises: b4408b79bedb
Create Date: 2025-11-15 09:50:05.581066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41af09a4efe2'
down_revision: Union[str, Sequence[str], None] = 'b4408b79bedb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
