"""email column at user table is made unique

Revision ID: ab207774670e
Revises: b7a748efa74a
Create Date: 2025-11-02 00:36:50.628013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab207774670e'
down_revision: Union[str, Sequence[str], None] = 'b7a748efa74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_unique_constraint('uq_users_emai', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_email",  "users",type_="unique")
    # ### end Alembic commands ###
