"""Add default for created_at and updated_at in reviews python time

Revision ID: b4408b79bedb
Revises: 543cb1eeaa5b
Create Date: 2025-11-08 21:35:14.318005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4408b79bedb'
down_revision: Union[str, Sequence[str], None] = '543cb1eeaa5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
