"""change book id to bid

Revision ID: b7a748efa74a
Revises: 371baf940eb1
Create Date: 2025-11-01 02:00:38.666368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7a748efa74a'
down_revision: Union[str, Sequence[str], None] = '371baf940eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'id', new_column_name='bid')
    # op.add_column('books', sa.Column('bid', sa.UUID(), nullable=False))
    # op.drop_index(op.f('ix_books_id'), table_name='books')
    # op.create_index(op.f('ix_books_bid'), 'books', ['bid'], unique=True)
    # op.drop_column('books', 'id')
    # op.create_unique_constraint(None, 'users', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'bid', new_column_name='id')
    # op.drop_constraint(None, 'users', type_='unique')
    # op.add_column('books', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    # op.drop_index(op.f('ix_books_bid'), table_name='books')
    # op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=True)
    # op.drop_column('books', 'bid')
    # ### end Alembic commands ###
