"""change in role of usermodel

Revision ID: d5f4661d39b8
Revises: ab207774670e
Create Date: 2025-11-02 02:21:29.703204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f4661d39b8'
down_revision: Union[str, Sequence[str], None] = 'ab207774670e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.create_index(op.f('ix_books_bid'), 'books', ['bid'], unique=True)
    op.create_unique_constraint(None, 'users', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_books_bid'), table_name='books')
    op.create_index(op.f('ix_books_id'), 'books', ['bid'], unique=True)
    # ### end Alembic commands ###
